"use client"

import React, { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "es"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("en")

  useEffect(() => {
    const saved = localStorage.getItem("humand-lang") as Language | null
    if (saved && (saved === "en" || saved === "es")) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem("humand-lang", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }
  return context
}

const translations = {
  en: {
    dashboard: "Dashboard",
    employees: "Employees",
    benefits: "Benefits",
    creditLoading: "Credit Loading",
    autoRules: "Automation Rules",
    analytics: "Analytics",
    regionsOffices: "Regions & Offices",
    totalCredits: "Total Credits",
    activeEmployees: "Active Employees",
    activeBenefits: "Active Benefits",
    redemptions: "Redemptions",
    search: "Search...",
    add: "Add",
    filter: "Filter",
    export: "Export",
    name: "Name",
    email: "Email",
    department: "Department",
    creditBalance: "Credit Balance",
    spent: "Spent",
    status: "Status",
    actions: "Actions",
    active: "Active",
    inactive: "Inactive",
    category: "Category",
    provider: "Provider",
    credits: "Credits",
    redemptionsCount: "Redemptions",
    bulkLoad: "Bulk Load",
    automaticRules: "Automatic Rules",
    language: "Language",
    // Navigation
    statistics: "Statistics",
    users: "Users",
    groups: "Groups",
    segmentation: "Segmentation",
    workSchedules: "Work Schedules",
    news: "News",
    knowledgeLibraries: "Knowledge Libraries",
    formsAndProcedures: "Forms & Procedures",
    settings: "Settings",
    autoLoads: "Automatic Loads",
    collapse: "Collapse",
    platformName: "Corporate Benefits Platform",
    benefitsGroup: "Benefits",
    employees: "Employees",
    // Dashboard
    creditsDashboard: "Credits Dashboard",
    dashboardSubtitle: "General tracking of credit usage on the platform",
    acquiredCredits: "Acquired Credits",
    totalAssignedCredits: "Total Assigned Credits",
    redeemedCredits: "Redeemed Credits",
    redemptionRate: "Redemption Rate",
    availableToAssign: "Available to assign",
    creditsLoadedVsRedeemed: "Credits loaded vs redeemed",
    redemptionsByCategory: "Redemptions by category",
    usageByDept: "Usage by department",
    recentActivity: "Recent Activity",
    loaded: "Loaded",
    redeemed: "Redeemed",
    vsPrevMonth: "vs previous month",
    // Bulk load
    bulkCreditLoad: "Bulk Credit Loading",
    bulkLoadSubtitle: "Load credits to multiple collaborators via CSV file",
    newBulkLoad: "New Bulk Load",
    loadsThisMonth: "Loads this month",
    totalCreditsLoaded: "Total credits loaded",
    usersReached: "Users reached",
    loadHistory: "Load History",
    date: "Date",
    file: "File",
    creditsPerUser: "Credits/user",
    total: "Total",
    createdBy: "Created by",
    completed: "Completed",
    failed: "Failed",
    processLoad: "Process Load",
    uploadCSV: "Upload your CSV file",
    dragDropCSV: "Drag a file or click to select",
    csvFormatLabel: "Expected format",
    csvFormatDesc: "The CSV must contain columns: email, credits.",
    creditsPerUserField: "Credits per user (if not specified in CSV)",
    loadReason: "Load reason",
    expirationDate: "Expiration date (optional)",
    downloadTemplate: "Download CSV template",
    csvTemplateDownloaded: "CSV template downloaded",
    fileSelected: "File selected",
    loadReasonPlaceholder: "E.g.: Monthly load March 2026",
    bulkLoadSuccess: "Bulk load processed successfully",
    cancel: "Cancel",
    // Individual load / Employees
    employeesSubtitle: "Manage your employees' credits individually or in bulk",
    employee: "Employee",
    loadedCredits: "Loaded Credits",
    usedCredits: "Used Credits",
    available: "Available",
    load: "Load",
    loadCredits: "Load Credits",
    creditAmount: "Credit amount",
    reason: "Reason",
    note: "Note (optional)",
    selectReason: "Select reason...",
    specialBonus: "Special Bonus",
    adjustment: "Adjustment",
    compensation: "Compensation",
    other: "Other",
    commentPlaceholder: "Internal comment about the load",
    searchByNameEmailDept: "Search by name, email or department...",
    filters: "Filters",
    // Benefits management
    benefitsManagement: "Benefits Management",
    benefitsManagementSubtitle: "Manage the catalog of benefits available to redeem",
    newBenefit: "New Benefit",
    benefitStatusActive: "Active",
    benefitStatusPaused: "Paused",
    edit: "Edit",
    view: "View",
    benefit: "Benefit",
    benefitName: "Benefit name",
    creditCost: "Credit cost",
    availableStock: "Available stock (optional)",
    description: "Description",
    imageOrEmoji: "Image or representative emoji",
    createBenefit: "Create Benefit",
    creditsLabel: "credits",
    redemptionsLabel: "redemptions",
    // Auto rules
    ruleTypesTab: "Rule Types",
    rulesTab: "Rules",
    historyTab: "History",
    newRuleType: "New Rule Type",
    newRule: "New Rule",
    backToRuleTypes: "Back to rule types",
    noRulesConfigured: "No rules configured",
    createFirstRule: "Create a new rule for this type",
    rule_s: "rule",
    rule_pl: "rules",
    persons: "people",
    trigger: "Trigger",
    lastRun: "Last run",
    ruleStatusActive: "Active",
    ruleStatusPaused: "Paused",
    editAction: "Edit",
    pauseRule: "Pause",
    activateRule: "Activate",
    historyTitle: "Execution History",
    executed: "Executed",
    newAutoRule: "New Automatic Rule",
    ruleName: "Rule name",
    triggerType: "Trigger type",
    periodicityLabel: "Periodicity (if applicable)",
    applyTo: "Apply to",
    createRule: "Create Rule",
    duplicateAction: "Duplicate",
    pauseAll: "Pause all",
    deleteAction: "Delete",
    // Analytics
    analyticsTitle: "Usage Analytics",
    analyticsSubtitle: "Insights on credit and benefit usage by collaborators",
    activeUsers: "Active Users",
    totalRedemptions: "Total Redemptions",
    avgRedemptionsPerUser: "Avg. redemptions/user",
    satisfaction: "Satisfaction",
    weeklyRedemptionTrend: "Weekly redemption trend",
    topRedeemedBenefits: "Most redeemed benefits",
    topUsersByUsage: "Top users by usage",
    creditsUsed: "credits used",
    redemptions_col: "redemptions",
    week: "Week",
    month: "Month",
    quarter: "Quarter",
    year: "Year",
    collaborator: "Collaborator",
    department: "Department",
  },
  es: {
    dashboard: "Dashboard",
    employees: "Empleados",
    benefits: "Beneficios",
    creditLoading: "Carga de Créditos",
    autoRules: "Reglas Automáticas",
    analytics: "Analítica",
    regionsOffices: "Regiones y sedes",
    totalCredits: "Créditos Totales",
    activeEmployees: "Empleados Activos",
    activeBenefits: "Beneficios Activos",
    redemptions: "Canjes",
    search: "Buscar...",
    add: "Agregar",
    filter: "Filtrar",
    export: "Exportar",
    name: "Nombre",
    email: "Email",
    department: "Departamento",
    creditBalance: "Saldo de Créditos",
    spent: "Gastado",
    status: "Estado",
    actions: "Acciones",
    active: "Activo",
    inactive: "Inactivo",
    category: "Categoría",
    provider: "Proveedor",
    credits: "Créditos",
    redemptionsCount: "Canjes",
    bulkLoad: "Carga Masiva",
    automaticRules: "Reglas Automáticas",
    language: "Idioma",
    // Navigation
    statistics: "Estadísticas",
    users: "Usuarios",
    groups: "Grupos",
    segmentation: "Segmentación",
    workSchedules: "Horarios laborales",
    news: "Noticias",
    knowledgeLibraries: "Librerías de conocimiento",
    formsAndProcedures: "Formularios y Trámites",
    settings: "Configuración",
    autoLoads: "Cargas automáticas",
    collapse: "Colapsar",
    platformName: "Plataforma de Beneficios Corporativos",
    benefitsGroup: "Beneficios",
    employees: "Colaboradores",
    // Dashboard
    creditsDashboard: "Dashboard de Créditos",
    dashboardSubtitle: "Seguimiento general del uso de créditos en la plataforma",
    acquiredCredits: "Créditos adquiridos",
    totalAssignedCredits: "Créditos totales asignados",
    redeemedCredits: "Créditos canjeados",
    redemptionRate: "Tasa de canje",
    availableToAssign: "Disponibles para asignar",
    creditsLoadedVsRedeemed: "Créditos cargados vs canjeados",
    redemptionsByCategory: "Canjes por categoría",
    usageByDept: "Uso por departamento",
    recentActivity: "Actividad reciente",
    loaded: "Cargados",
    redeemed: "Canjeados",
    vsPrevMonth: "vs mes anterior",
    // Bulk load
    bulkCreditLoad: "Carga masiva de créditos",
    bulkLoadSubtitle: "Cargá créditos a múltiples colaboradores mediante archivo CSV",
    newBulkLoad: "Nueva carga masiva",
    loadsThisMonth: "Cargas este mes",
    totalCreditsLoaded: "Créditos cargados total",
    usersReached: "Usuarios alcanzados",
    loadHistory: "Historial de cargas",
    date: "Fecha",
    file: "Archivo",
    creditsPerUser: "Créditos/usuario",
    total: "Total",
    createdBy: "Creado por",
    completed: "Completado",
    failed: "Fallido",
    processLoad: "Procesar carga",
    uploadCSV: "Subí tu archivo CSV",
    dragDropCSV: "Arrastrá un archivo o hacé click para seleccionar",
    csvFormatLabel: "Formato esperado",
    csvFormatDesc: "El CSV debe contener las columnas: email, creditos.",
    creditsPerUserField: "Créditos por usuario (si no se especifica en el CSV)",
    loadReason: "Motivo de la carga",
    expirationDate: "Fecha de expiración (opcional)",
    downloadTemplate: "Descargar plantilla CSV",
    csvTemplateDownloaded: "Plantilla CSV descargada",
    fileSelected: "Archivo seleccionado",
    loadReasonPlaceholder: "Ej: Carga mensual marzo 2026",
    bulkLoadSuccess: "Carga masiva procesada exitosamente",
    cancel: "Cancelar",
    // Individual load / Employees
    employeesSubtitle: "Gestioná créditos de tus colaboradores de forma individual o masiva",
    employee: "Colaborador",
    loadedCredits: "Créditos cargados",
    usedCredits: "Créditos usados",
    available: "Disponible",
    load: "Cargar",
    loadCredits: "Cargar créditos",
    creditAmount: "Cantidad de créditos",
    reason: "Motivo",
    note: "Nota (opcional)",
    selectReason: "Seleccionar motivo...",
    specialBonus: "Bonus especial",
    adjustment: "Ajuste",
    compensation: "Compensación",
    other: "Otro",
    commentPlaceholder: "Comentario interno sobre la carga",
    searchByNameEmailDept: "Buscar por nombre, email o departamento...",
    filters: "Filtros",
    // Benefits management
    benefitsManagement: "Gestión de Beneficios",
    benefitsManagementSubtitle: "Administrá el catálogo de beneficios disponibles para canjear",
    newBenefit: "Nuevo beneficio",
    benefitStatusActive: "Activo",
    benefitStatusPaused: "Pausado",
    edit: "Editar",
    view: "Ver",
    benefit: "Beneficio",
    benefitName: "Nombre del beneficio",
    creditCost: "Costo en créditos",
    availableStock: "Stock disponible (opcional)",
    description: "Descripción",
    imageOrEmoji: "Imagen o emoji representativo",
    createBenefit: "Crear beneficio",
    creditsLabel: "créditos",
    redemptionsLabel: "canjes",
    // Auto rules
    ruleTypesTab: "Tipos de reglas",
    rulesTab: "Reglas",
    historyTab: "Historial",
    newRuleType: "Nuevo tipo de regla",
    newRule: "Nueva regla",
    backToRuleTypes: "Volver a tipos de reglas",
    noRulesConfigured: "No hay reglas configuradas",
    createFirstRule: "Creá una nueva regla para este tipo",
    rule_s: "regla",
    rule_pl: "reglas",
    persons: "personas",
    trigger: "Trigger",
    lastRun: "Última ejecución",
    ruleStatusActive: "Activa",
    ruleStatusPaused: "Pausada",
    editAction: "Editar",
    pauseRule: "Pausar",
    activateRule: "Activar",
    historyTitle: "Historial de ejecuciones",
    executed: "Ejecutada",
    newAutoRule: "Nueva regla automática",
    ruleName: "Nombre de la regla",
    triggerType: "Tipo de trigger",
    periodicityLabel: "Periodicidad (si aplica)",
    applyTo: "Aplicar a",
    createRule: "Crear regla",
    duplicateAction: "Duplicar",
    pauseAll: "Pausar todas",
    deleteAction: "Eliminar",
    // Analytics
    analyticsTitle: "Analíticas de uso",
    analyticsSubtitle: "Insights sobre el uso de créditos y beneficios por parte de los colaboradores",
    activeUsers: "Usuarios activos",
    totalRedemptions: "Canjes totales",
    avgRedemptionsPerUser: "Promedio canjes/usuario",
    satisfaction: "Satisfacción",
    weeklyRedemptionTrend: "Tendencia de canjes semanal",
    topRedeemedBenefits: "Top beneficios más canjeados",
    topUsersByUsage: "Colaboradores con mayor uso",
    creditsUsed: "créditos usados",
    redemptions_col: "canjes",
    week: "Semana",
    month: "Mes",
    quarter: "Trimestre",
    year: "Año",
    collaborator: "Colaborador",
    department: "Departamento",
  },
}
